import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const myfont = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'], 
});

export const metadata: Metadata = {
  title: "Simple U.I Design",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={myfont.className}
      >
        {children}
      </body>
    </html>
  );
}
